name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up project
        run: bin/setup

      - name: Run Standard
        run: bundle exec standardrb --fail-level A

      - name: Run Annotate
        run: bundle exec annotate --frozen

      - name: Run Chusaku
        run: bundle exec chusaku --dry-run --exit-with-error-on-annotation

      - name: Run test suite
        run: bin/rails test
